"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

# Change the default prompt format
format = """\
$all[╰─ ](238)$character"""

# Shows the username
[username]
style_user = "white bold"
style_root = "black bold"
format = "者 [$user]($style) "
disabled = true              # disable in powershell
show_always = true

[hostname]
ssh_only = false
format = "on [$hostname](bold yellow) "
disabled = true

[directory]
# truncation_length = 30
truncate_to_repo = false
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "197"
read_only = "  "
format = "[$path]($style)[$read_only]($read_only_style) "
substitutions = { "\\\\" = "/", "C:\\\\" = "C:/" }

# [directory.substitutions]
# "C:\\" = "C:/"
# "\\" = "/"

[git_branch]
symbol = "   "
format = "[$symbol$branch (:$remote_branch)](bold green)"

# [git_status]
# ahead = "⇡${count}"
# diverged = "⇕⇡${ahead_count}⇣${behind_count}"
# behind = "⇣${count}"
# [git_branch]
# format='(bold green)[  ](bold base)[$symbol$branch(:$remote_branch)](bold bg:base fg:text)(bold base)'
# style='bold green'
# symbol=" "
